name: Subir Imágenes a GitHub

# Este flujo se activará cuando se suban nuevas imágenes a la carpeta 'selfies/'
on:
  push:
    paths:
      - 'selfies/**'  # Cambios en cualquier archivo dentro de la carpeta selfies

jobs:
  upload-images:
    runs-on: ubuntu-latest  # Esto indica que la acción se ejecutará en un entorno Ubuntu

    steps:
    - name: Check out repository
      uses: actions/checkout@v3  # Este paso obtiene el código más reciente del repositorio

    - name: Configurar Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Subir nuevas imágenes
      run: |
        git add selfies/*  # Esto agrega todas las imágenes en la carpeta selfies
        git commit -m "Subiendo nuevas selfies"  # Hacemos commit de las imágenes
        git push  # Luego subimos las imágenes al repositorio

